version: '2'

services:
  postgres:
    image: rpopuc/postgres:11
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  mongo:
    image: mongo:4-xenial
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis:5.0-alpine
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
